import type { NextPage } from "next";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";

interface LayoutProps {
  children: React.ReactNode;
}

const Layout: NextPage<LayoutProps> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav></nav>

      <main>{children}</main>

      <footer></footer>
    </div>
  );
};

export default Layout;
